### ISSUE TITLE
Garage door type

### ISSUE THREAD

**Issue by MervinDelfin** [leoyn/gira-homeserver-api#2]
Your readme states that a garage door is type "20". I tested it and mine only works if i specify the type as 1.

**Comment by leoyn** [comment]
Okay. I'll check this later. I probably depends on how your homeserver is configured.
I might end up creating a parser for the device list xml file which then gives you the appropriate device types.

**Comment by leoyn** [comment]
Commit 6f93d9d4f4a9a173b7054fa62226771f18b9d4d5 fixes problems with differentiating device types used by the GIRA Homeserver described in #2.
